### ISSUE TITLE
722行为什么要加一张牌到公共牌呢

### ISSUE THREAD

**Issue by walking-with-linght** [yangxintao123/texasCardType#2]
https://github.com/qlyxt/texasCardType/blob/cdbcf5033c2b1e433474b37ecf55ab1b4fe7ba6a/texas_card_type.lua#L722

不是很理解。

**Comment by qlyxt** [comment]
publicCardCp是 当前公共牌的拷贝；遍历所有的牌（不包括手牌和公共牌），放到公共牌里，再遍历所有手牌，找到跟当前公共牌合成牌型最大的手牌组下标，当前牌就是本次牌型最大的手牌的out

**Comment by walking-with-linght** [comment]
懂了
另外有个问题，计算胜率是几个玩家合并起来为1？
但实际上游戏中并不会这样做，提示的胜率只是自己的牌型大小，并不可能是所有胜率加起来为1（这样很容易穿帮导致弃牌）。
可以增加一个这个接口么（问题1）。
另外我增加了一个`get_max_five_cards`接口，获取最大的五张牌，
在https://github.com/qlyxt/texasCardType/blob/cdbcf5033c2b1e433474b37ecf55ab1b4fe7ba6a/texas_card_type.lua#L448C6-L448C6修改如下：
![image](https://github.com/qlyxt/texasCardType/assets/31840262/590bfc2a-a7ed-4a28-a70e-0b9dd7ae049a)

根据牌型，在调用调用`analysisCardData_`函数，利用里面的`uniColor` `smThourCards`等等table来组合成最大的五张牌，具体代码如下：
`--返回牌型最大的五张牌
local function get_max_five_cards(hand_cards,public_cards,_card_type)
    local all = {}
    for i,v in pairs(hand_cards) do
        table.insert(all,v)
    end
    for i,v in pairs(public_cards) do
        table.insert(all,v)
    end
    if #all <= 5 then
        return all
    end

    local all_cid = {}--客户端点数
    allCardsSidToCid_(hand_cards,all_cid)
    allCardsSidToCid_(public_cards,all_cid)

    local res = analysisCardData_(all_cid)
    print(cjson.encode(res))
    local ret = {}
    local tp = _card_type or getCardType(hand_cards,public_cards)
    if tp == CARD_TYPE.ROYAL_STRAIGHT_FLUSH then--皇家同花顺
        for i,v in pairs(res.uniColor) do
            if #v >= 5 then
                local ret = {}
                for j,k in ipairs(v) do
                    table.insert(ret,cardCid2Sid_(k.rawCid))
                    if #ret >= 5 then
                        break
                    end
                end
                return ret
            end
        end
    elseif tp == CARD_TYPE.STRAIGHT_FLUSH then--同花顺
        for i,v in pairs(res.uniColor) do
            if #v >= 5 then
                local ret = {}
                for j,k in ipairs(v) do
                    table.insert(ret,cardCid2Sid_(k.rawCid))
                    if #ret >= 5 then
                        break
                    end
                end
                return ret
            end
        end
    elseif tp == CARD_TYPE.FOUR_OF_A_KIND then--四条
        table.insert(ret,cardCid2Sid_(res.smThourCards[1].rawCid))
        table.insert(ret,cardCid2Sid_(res.smThourCards[2].rawCid))
        table.insert(ret,cardCid2Sid_(res.smThourCards[3].rawCid))
        table.insert(ret,cardCid2Sid_(res.smThourCards[4].rawCid))
        
        --TODO 有可能单牌也没有
        if res.smSingleCards[1] then--单牌
            table.insert(ret,cardCid2Sid_(res.smSingleCards[1].rawCid))--外加一张最大的单牌
        elseif res.smSecondCards[1] then--对子
            table.insert(ret,cardCid2Sid_(res.smSecondCards[1].rawCid))
        elseif res.smThreeCards[1] then--三个
            table.insert(ret,cardCid2Sid_(res.smThreeCards[1].rawCid))
        end

    elseif tp == CARD_TYPE.FULL_HOUSE then--葫芦
        table.insert(ret,cardCid2Sid_(res.smThreeCards[1].rawCid))
        table.insert(ret,cardCid2Sid_(res.smThreeCards[2].rawCid))
        table.insert(ret,cardCid2Sid_(res.smThreeCards[3].rawCid))
        table.insert(ret,cardCid2Sid_(res.smSecondCards[1].rawCid))
        table.insert(ret,cardCid2Sid_(res.smSecondCards[2].rawCid))
    elseif tp == CARD_TYPE.FLUSH then--同花
        for i,v in pairs(res.uniColor) do
            if #v >= 5 then
                local ret = {}
                for j,k in ipairs(v) do
                    table.insert(ret,cardCid2Sid_(k.rawCid))
                    if #ret >= 5 then
                        break
                    end
                end
                return ret
            end
        end
    elseif tp == CARD_TYPE.STRAIGHT then--顺子
        local shunzi = getMaxLengLink_(res.cidData)
        for i,v in pairs(shunzi) do
            table.insert(ret,cardCid2Sid_(v.rawCid))
            if #ret >= 5 then
                break
            end
        end
    elseif tp == CARD_TYPE.THREE_OF_A_KIND then--三条
        table.insert(ret,cardCid2Sid_(res.smThreeCards[1].rawCid))
        table.insert(ret,cardCid2Sid_(res.smThreeCards[2].rawCid))
        table.insert(ret,cardCid2Sid_(res.smThreeCards[3].rawCid))
        table.insert(ret,cardCid2Sid_(res.smSingleCards[1].rawCid))
        table.insert(ret,cardCid2Sid_(res.smSingleCards[2].rawCid))
    elseif tp == CARD_TYPE.TWO_PAIRS then--两对
        table.insert(ret,cardCid2Sid_(res.smSecondCards[1].rawCid))
        table.insert(ret,cardCid2Sid_(res.smSecondCards[2].rawCid))
        table.insert(ret,cardCid2Sid_(res.smSecondCards[3].rawCid))
        table.insert(ret,cardCid2Sid_(res.smSecondCards[4].rawCid))
        table.insert(ret,cardCid2Sid_(res.smSingleCards[1].rawCid))
    elseif tp == CARD_TYPE.PAIR then--对子
        table.insert(ret,cardCid2Sid_(res.smSecondCards[1].rawCid))
        table.insert(ret,cardCid2Sid_(res.smSecondCards[2].rawCid))
        table.insert(ret,cardCid2Sid_(res.smSingleCards[1].rawCid))
        table.insert(ret,cardCid2Sid_(res.smSingleCards[2].rawCid))
        table.insert(ret,cardCid2Sid_(res.smSingleCards[3].rawCid))
    elseif tp == CARD_TYPE.HIGH_CARD then--高牌
        table.insert(ret,cardCid2Sid_(res.smSingleCards[1].rawCid))
        table.insert(ret,cardCid2Sid_(res.smSingleCards[2].rawCid))
        table.insert(ret,cardCid2Sid_(res.smSingleCards[3].rawCid))
        table.insert(ret,cardCid2Sid_(res.smSingleCards[4].rawCid))
        table.insert(ret,cardCid2Sid_(res.smSingleCards[5].rawCid))
    end
    return ret
end`
我不知道对https://github.com/qlyxt/texasCardType/blob/cdbcf5033c2b1e433474b37ecf55ab1b4fe7ba6a/texas_card_type.lua#L448C6-L448C6这里的改动是否会影响到比牌结果（问题2）。。

**Comment by qlyxt** [comment]
问题2，对 analysisCardData_ 修改会影响比牌，比如葫芦牌型的时候

你可以参考一下 analysisCardData_ 方法写一个新的方法，来满足你获取五张最大牌的需求

**Comment by qlyxt** [comment]
问题1，正常情况下，客户端只知道自己的手牌，服务器不会明文下发桌上其他人的手牌；此处的胜率，应该是两或多个玩家同时allin时算的各自胜率吧；时间长了，我也忘了当时的策划需求了，见谅

**Comment by walking-with-linght** [comment]
感谢大哥。
大哥之前的项目还留有代码么，可以学习下么，还有主池边池分奖金的概念太模糊，网上资料太少了....

**Comment by walking-with-linght** [comment]
推荐另外一个算法
https://github.com/iRusher/texas_poker_evaluator

**Comment by qlyxt** [comment]
可以，二进制实现性能上更好
